// OptionsAppState
export const CHANGE_IS_SHOW_CONTENT_NOTES = 'CHANGE_IS_SHOW_CONTENT_NOTES'
export const CHANGE_TYPE_NOTE = 'CHANGE_TYPE_NOTE'
export const SET_APP_COLOR = 'SET_APP_COLOR'
export const SET_FONT_FAMILY = 'SET_FONT_FAMILY'
export const SET_FONT_SIZE = 'SET_FONT_SIZE'

//NoteState
export const NEW_CATEGORY = 'NEW_CATEGORY'
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY'
export const ADD_NOTE = 'ADD_NOTE'
export const UPDATE_NOTE = 'UPDATE_NOTE'
export const REMOVE_NOTE = 'REMOVE_NOTE'
export const SELECTED_NOTE = 'SELECTED_NOTE'
export const ADD_TRASH = 'ADD_TRASH'
export const REMOVE_TRASH = 'REMOVE_TRASH'
export const REMOVE_ALL_TRASH = 'REMOVE_ALL_TRASH'
export const REESTABLISH_TRASH = 'REESTABLISH_TRASH'

//ModalState
export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDDEN_MODAL = 'HIDDEN_MODAL'